name: Docker Image CI (Docker Hub)

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  IMAGE_NAME: hamzasdq11/pathway-genii   # your Docker Hub repo (as created)
  DOCKERFILE: ./Dockerfile               # change if your Dockerfile is NOT at repo root
  CONTEXT: .                             # change if the build context is a subfolder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
